//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefereeSqad
    {
        public int AppointmentId { get; set; }
        public int RefereeId { get; set; }
        public int RefereeTypeId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Referee Referee { get; set; }
        public virtual RefereeType RefereeType { get; set; }
    }
}
